import { getOptionalEnv, requireEnv } from '@/lib/server/config';

type ModulateSignals = {
  intimidation?: number;
  stress?: number;
  defensiveness?: number;
  confidenceMismatch?: number;
};

export async function analyzeWithModulate(file: File, entityId: string): Promise<{ signals: ModulateSignals; summary: string }> {
  const baseUrl = requireEnv('MODULATE_BASE_URL');
  const apiKey = requireEnv('MODULATE_API_KEY');

  const formData = new FormData();
  formData.append('file', file);
  formData.append('entityId', entityId);

  const endpoint = getOptionalEnv('MODULATE_ANALYZE_PATH') ?? '/analyze';
  const normalizedBase = baseUrl.replace(/\/+$/, '');
  const normalizedPath = endpoint.startsWith('/') ? endpoint : `/${endpoint}`;
  const response = await fetch(`${normalizedBase}${normalizedPath}`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`
    },
    body: formData
  });

  if (!response.ok) {
    const details = await response.text().catch(() => '');
    throw new Error(`Modulate request failed (${response.status}): ${details}`);
  }

  const payload = (await response.json()) as {
    signals?: ModulateSignals;
    summary?: string;
  };

  return {
    signals: payload.signals ?? {},
    summary: payload.summary ?? 'Voice signal generated by Modulate integration.'
  };
}
